CNStyleShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),

    path('dj-admin/', admin.site.urls),

    path('', include('shop.urls')),

    path('cart/', include('cart.urls')),

    path('account/', include('accounts.urls')),

    path('admin/', include('products.urls')),

    path('', include('articles.urls')), # มีทั้งส่วนของแอดมินและผู้้ใช้

    path('', include('orders.urls')), # มีทั้งส่วนของแอดมินและผู้้ใช้

    path('admin/', include('dashboard.urls')),
]

# เสริมสำหรับเสิร์ฟ Media Files ในโหมด Development
if settings.DEBUG:
    # สำหรับ media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # สำหรับ django-browser-reload
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

cart/urls.py
from django.urls import path
from .views import AddToCartView, CartDetailView, RemoveCartItemView, UpdateCartView

urlpatterns = [
    path('add/<int:product_id>', AddToCartView.as_view(), name='add_cart'),
    path("", CartDetailView.as_view(), name="cart_detail"),
    path('update/<int:pk>/', UpdateCartView.as_view(), name='update_cart'),
    path("remove/<int:pk>/", RemoveCartItemView.as_view(), name="remove_cart_item"),
]

orders/urls.py
from django.urls import path
from .views import OrderListView, OrderDetailView, CartCheckoutView, BuyNowView, PaymentView, MyOrdersView, \
    CancelOrderView, ReviewView

urlpatterns = [
    path('admin/order/list', OrderListView.as_view(), name='order_list'),
    path('admin/order/detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('buy-now/', BuyNowView.as_view(), name='buy_now'),
    path("checkout/", CartCheckoutView.as_view(), name="checkout"),
    path('payment/<int:order_id>/', PaymentView.as_view(), name='payment'),
    path("my-orders/", MyOrdersView.as_view(), name="my_orders"),
    path('cancel_order/<int:order_id>/', CancelOrderView.as_view(), name='cancel_order'),
    path('review/<int:item_id>/', ReviewView.as_view(), name='review'),

]

orders/models.py
from django.db import models
from accounts.models import UserProfile
from products.models import Product
import uuid
from datetime import datetime
from django.utils import timezone


# ฟังก์ชันสำหรับกำหนดเส้นทางการอัปโหลดรูปภาพของสลิปโอนเงิน
def upload_to(instance,filename):
    return f"payments/{instance.id}_{filename}"

class Order(models.Model):
    PaymentMethod = (
        ('slip', 'แนบสลิป'),
    )

    STATUS = (
        ('pending', 'รอการชำระเงิน'),
        ('paid', 'จ่ายแล้ว'),
        ('completed', 'สำเร็จ'),
        ('cancelled', 'ยกเลิก'),
    )

    order_code = models.CharField(max_length=20, unique=True, editable=False) # ไม่แสดงในฟอร์มการสร้างหรือการแก้ไขข้อมูล
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='orders')
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10)
    address = models.TextField()
    total_price = models.IntegerField()
    payment_method = models.CharField(max_length=50, choices=PaymentMethod)
    payment_image = models.ImageField(upload_to=upload_to, blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='pending')
    order_date = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"หมายเลขคำสั่งซื้อ: {self.order_code} - ชื่อ: {self.full_name} | ราคารวม: {self.total_price} บาท | สถานะ: {self.get_status_display()}"

    def save(self, *args, **kwargs):
        if not self.order_code:
            while True:
                # สร้าง order_code
                unique_part = uuid.uuid4().hex[:8]# ใช้เลขและตัวอักษร 8 หลักจาก UUID
                self.order_code = f"{datetime.now().strftime('%y%m%d')}{unique_part}"
                if not Order.objects.filter(order_code=self.order_code).exists():
                    break
        super().save(*args, **kwargs)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.IntegerField()
    color = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    unit_price = models.IntegerField()

    def __str__(self):
        return f"{self.id} | หมายเลขคำสั่งซื้อ: {self.order.order_code} | สินค้า: {self.product.name} - จำนวน: {self.quantity} | สี: {self.color} | ขนาด: {self.size} | ราคาต่อหน่วย: {self.unit_price} บาท"

    # จะถูกเรียกใช้งานได้เหมือนฟิลด์ (attribute) แทนที่จะเป็นฟังก์ชัน
    @property
    def total_price(self):
        return self.quantity * self.unit_price

orders/forms.py
from django import forms
from .models import Order
from .models import Order, OrderItem

class OrderFilterForm(forms.Form):
    STATUS_CHOICES = [('', '--- สถานะทั้งหมด ---')] + list(Order.STATUS)

    search = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'px-4 py-2 border border-gray-300 rounded-md w-full',
            'placeholder': 'ค้นหา หมายเลขคำสั่งซื้อ, ชื่อ, เบอร์โทร',
            'type': 'search'
        })
    )

    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        required=False,
        widget=forms.Select(attrs={
            'class': 'border border-gray-300 bg-white px-4 py-2 pr-10 rounded-md text-gray-700 w-full'
        })
    )

    date_from = forms.DateField(
        required=False,
        label='จากวันที่',
        widget=forms.DateInput(attrs={
            'class': 'px-4 py-2 border border-gray-300 rounded-md w-full text-gray-700',
            'type': 'date'
        })
    )

    date_to = forms.DateField(
        required=False,
        label='ถึงวันที่',
        widget=forms.DateInput(attrs={
            'class': 'px-4 py-2 border border-gray-300 rounded-md w-full text-gray-700',
            'type': 'date'
        })
    )

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['full_name', 'phone', 'address', 'payment_method', 'payment_image']

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, FormView
from django.views import View

from cart.models import Cart
from dashboard.models import Review
from products.models import Product, ProductOption
from .forms import OrderFilterForm
from .models import Order, OrderItem
from .forms import OrderForm

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest

# แอดมิน
class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'admin_login'
    model = Order
    template_name = 'orders/admin/order_list.html'
    paginate_by = 10 # แบ่งหน้า 10 รายการ

    def get_queryset(self):
        # รับค่าค้นหาจาก URL
        query = self.request.GET.get('search', '').strip()  # กรณีที่ไม่มีคำค้นหาจะเป็นค่าว่าง และตัดช่องว่างหัวท้ายออก
        status_filter = self.request.GET.get('status', '')
        date_from = self.request.GET.get('date_from', '')
        date_to = self.request.GET.get('date_to', '')


        orders = Order.objects.all().order_by('-id') # จัดเรียงจากใหม่ไปเก่า

        if query:
            orders = orders.filter(
                Q(order_code__icontains=query) |
                Q(full_name__icontains=query) |
                Q(phone__icontains=query)
            )

        if status_filter:
            orders = orders.filter(status=status_filter)

        if date_from and date_to:
            orders = orders.filter(order_date__date__range=[date_from, date_to])
        elif date_from:
            orders = orders.filter(order_date__date__gte=date_from)  # ค้นหาตั้งแต่วันที่เลือกขึ้นไป
        elif date_to:
            orders = orders.filter(order_date__date__lte=date_to)  # ค้นหาตั้งแต่วันที่เลือกลงไป

        return orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        query_params = self.request.GET.copy()  # คัดลอก query parameters
        query_params.pop('page', None)  # ลบพารามิเตอร์ 'page'

        context['form'] = OrderFilterForm(self.request.GET)
        context['query_params'] = query_params.urlencode()  # แปลงเป็น query string ที่ใช้ใน URL

        return context

class OrderDetailView(LoginRequiredMixin, DetailView):
    login_url = 'admin_login'
    model = Order
    template_name = 'orders/admin/order_detail.html'
    context_object_name = 'order'



# ผู้ใช้
class BuyNowView(LoginRequiredMixin, FormView):
    login_url = 'login'
    template_name = 'orders/user/checkout.html'
    form_class = OrderForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.request.GET.get("product_id")
        option_id = self.request.GET.get("option_id")
        quantity = int(self.request.GET.get("quantity", 1))

        product = get_object_or_404(Product, id=product_id)
        option = get_object_or_404(ProductOption, id=option_id)

        total_price = option.price * quantity
        user = self.request.user

        context.update({
            "user": user,
            "items": [{
                "product": product,
                "product_option": option,
                "quantity": quantity,
                "unit_price": option.price,
                "item_price": total_price, # คือ ราคารวมของแต่ละสินค้า
            }],
            "total_price": total_price, # ราคารวมทั้งหมด
            "is_buynow": True,
            "product": product,
        })

        return context

    def form_valid(self, form):
        """ สร้าง Order และ OrderItem แล้ว Redirect ไปยังหน้าชำระเงิน """
        option_id = self.request.POST.get("option_id")
        quantity = int(self.request.POST.get("quantity", 1))

        option = get_object_or_404(ProductOption, id=option_id)
        product = option.product
        total_price = option.price * quantity

        order = form.save(commit=False)
        order.user = self.request.user
        order.total_price = total_price
        order.status = "pending"
        order.save()

        # เพิ่มสินค้าเข้า OrderItem
        OrderItem.objects.create(
            order=order,
            product=product,
            color=option.color,
            size=option.size,
            quantity=quantity,
            unit_price=option.price,
        )

        return HttpResponseRedirect(reverse_lazy('payment', kwargs={'order_id': order.id}))

class CartCheckoutView(LoginRequiredMixin, FormView):
    login_url = 'login'
    template_name = 'orders/user/checkout.html'
    form_class = OrderForm

    def dispatch(self, request, *args, **kwargs):
        """ ตรวจสอบตะกร้า หากไม่มีสินค้าให้ redirect ไปยังหน้าตะกร้า """
        user = self.request.user
        cart = Cart.objects.get(user=user)

        if not cart.items.exists():
            return redirect('cart_detail')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        cart = Cart.objects.get(user=user)

        context.update({
            "user": user,
            "items": cart.items.all(),
            "total_price": cart.get_total_price(),  # ราคารวมทั้งหมด
        })

        return context

    def form_valid(self, form):
        user = self.request.user
        cart = Cart.objects.get(user=user)

        # สร้างคำสั่งซื้อ
        order = form.save(commit=False)
        order.user = user
        order.total_price = cart.get_total_price()
        order.status = "pending"
        order.save()

        # บันทึกสินค้าจาก Cart ไปยัง OrderItem
        for item in cart.items.all():
            OrderItem.objects.create(
                order=order,
                product=item.product,
                color=item.product_option.color,
                size=item.product_option.size,
                quantity=item.quantity,
                unit_price=item.product_option.price,
            )

        # ลบสินค้าออกจากตะกร้า
        cart.items.all().delete()

        return HttpResponseRedirect(reverse_lazy('payment', kwargs={'order_id': order.id}))

class CancelOrderView(LoginRequiredMixin, View):
    login_url = 'login'

    def post(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)

        if order.status == 'pending':
            # เปลี่ยนสถานะของคำสั่งซื้อเป็น 'cancelled'
            order.status = 'cancelled'
            order.save()
            return HttpResponse(status=204)
        else:
            return HttpResponseBadRequest("ไม่สามารถยกเลิกคำสั่งซื้อนี้ได้") # ส่งข้อผิดพลาด 400 พร้อมข้อความ

class PaymentView(LoginRequiredMixin, View):
    login_url = 'login'

    def get(self, request, order_id):
        """ แสดงหน้าชำระเงินพร้อมรายละเอียดคำสั่งซื้อ """
        order = get_object_or_404(Order, id=order_id, user=request.user)
        order_items = OrderItem.objects.filter(order=order)

        context = {
            "order": order,
            "order_items": order_items,
        }
        return render(request, "orders/user/payment.html", context)

    def post(self, request, order_id):
        """ อัพโหลดสลิปและเปลี่ยนสถานะเป็น 'จ่ายแล้ว' """
        order = get_object_or_404(Order, id=order_id, user=request.user)
        slip = request.FILES.get("payment_image")

        if slip:
            order.payment_image = slip
            order.status = "paid"  # เปลี่ยนสถานะเป็นจ่ายแล้ว
            order.save()
            return redirect(f"{reverse('my_orders')}?tab=paid")

        return redirect("payment", order_id=order.id)

class ReviewView(LoginRequiredMixin, View):
    login_url = 'login'

    def get(self, request, item_id):
        """ ดึงฟอร์มรีวิวและแสดงเป็น modal """
        order_item = get_object_or_404(OrderItem, id=item_id)
        return render(request, 'orders/user/review_form.html', {'order_item': order_item})

    def post(self, request, item_id):
        order_item = get_object_or_404(OrderItem, id=item_id)
        rating = int(request.POST.get("rating"))
        comment = request.POST.get("comment")

        # บันทึกรีวิว
        review = Review.objects.create(
            order_item=order_item,
            product=order_item.product,
            user=request.user,
            rating=rating,
            comment=comment
        )
        return redirect(f"{reverse('my_orders')}?tab=completed")

class MyOrdersView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = "orders/user/my_orders.html"
    context_object_name = "items"
    paginate_by = 10

    ORDER_TABS = {
        "pending": "รอการชำระเงิน",
        "paid": "รอการอนุมัติ",
        "completed": "สำเร็จ",
        "cancelled": "ยกเลิก",
        "reviews": "ประวัติรีวิว"
    }

    def get_queryset(self):
        """ กำหนด queryset ตามแท็บที่เลือก """
        tab = self.request.GET.get("tab", "pending")  # ค่าเริ่มต้นเป็น 'pending'
        self.current_tab = tab  # เก็บค่าแท็บปัจจุบันเพื่อใช้ใน context

        if tab == "reviews":
            return Review.objects.filter(user=self.request.user).order_by("-created_at")
        return Order.objects.filter(user=self.request.user, status=tab).order_by("-updated_at")

    def get_context_data(self, **kwargs):
        """ เพิ่มค่า tab และ item_type เข้าไปใน context """
        context = super().get_context_data(**kwargs)

        query_params = self.request.GET.copy()  # คัดลอก query parameters
        query_params.pop('page', None)  # ลบพารามิเตอร์ 'page' ถ้ามีอยู่ เพื่อป้องกันค่าหน้าเก่าถูกส่งไป

        context["tabs"] = self.ORDER_TABS
        context["current_tab"] = self.current_tab
        context["item_type"] = "review" if self.current_tab == "reviews" else "order"
        context['query_params'] = query_params.urlencode()  # แปลงเป็น query string ที่ใช้ใน URL

        return context

templates/orders/admin/order_detail.html
<div class="max-w-2xl mx-auto bg-white rounded-lg shadow p-6">
    <!-- ส่วนหัวแสดงรายละเอียดคำสั่งซื้อ -->
    <h1 class="text-2xl font-bold mb-6 flex items-center text-gray-800">
        รายละเอียดคำสั่งซื้อ:
        <span class="ml-2 text-blue-600">{{ order.order_code }}</span>
    </h1>

    <!-- ข้อมูลของลูกค้า -->
    <div class="mb-6 p-6 border border-gray-300 rounded-lg shadow">
        <h2 class="text-xl font-semibold mb-4 flex items-center text-gray-800">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-blue-500 mr-3">
                <path fill-rule="evenodd" d="M7.5 6a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0ZM3.751 20.105a8.25 8.25 0 0 1 16.498 0 .75.75 0 0 1-.437.695A18.683 18.683 0 0 1 12 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 0 1-.437-.695Z" clip-rule="evenodd" />
            </svg>
            ข้อมูลลูกค้า
        </h2>

        <div class="space-y-3 px-6 text-gray-600">
            <p>
                <span class="font-semibold text-gray-700 mr-1">ชื่อ:</span>
                {{ order.full_name }}
            </p>
            <p>
                <span class="font-semibold text-gray-700 mr-1">เบอร์โทร:</span>
                {{ order.phone }}
            </p>
        </div>
    </div>

    <!-- ที่อยู่ในการจัดส่ง -->
    <div class="mb-6 p-6 border border-gray-300 rounded-lg shadow">
        <h2 class="text-xl font-semibold mb-4 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-blue-500 mr-2">
              <path fill-rule="evenodd" d="m11.54 22.351.07.04.028.016a.76.76 0 0 0 .723 0l.028-.015.071-.041a16.975 16.975 0 0 0 1.144-.742 19.58 19.58 0 0 0 2.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 0 0-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 0 0 2.682 2.282 16.975 16.975 0 0 0 1.145.742ZM12 13.5a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" clip-rule="evenodd" />
            </svg>
            ที่อยู่ในการจัดส่ง
        </h2>

        <p class="px-6 text-gray-600">{{ order.address }}</p>
    </div>

    <!-- รายละเอียดการสั่งซื้อ -->
    <div class="mb-6 p-6 border border-gray-300 rounded-lg shadow">
        <h2 class="text-xl font-semibold mb-4 flex items-center">
            รายละเอียดการสั่งซื้อ
        </h2>
        <div class="space-y-3 px-6 text-gray-600">
            <p>
                <span class="font-semibold text-gray-700 mr-1">ราคารวมทั้งหมด:</span>
                <span class="text-xl font-semibold text-blue-600">{{ order.total_price }} บาท</span>
            </p>
            <p>
                <span class="font-semibold text-gray-700 mr-1">วิธีการชำระเงิน:</span>
                {{ order.get_payment_method_display }}
            </p>
            <p>
                <span class="font-semibold text-gray-700 mr-1">สถานะ:</span>
                <span class="
                    {% if order.status == 'pending' %}
                        bg-yellow-200 text-yellow-700
                    {% elif order.status == 'paid' %}
                        bg-blue-200 text-blue-700
                    {% elif order.status == 'completed' %}
                        bg-green-200 text-green-700
                    {% elif order.status == 'cancelled' %}
                        bg-red-200 text-red-700
                    {% endif %}
                    px-3 py-1 rounded-full font-semibold
                ">
                    {{ order.get_status_display }}
                </span>
            </p>
            <p>
                <span class="font-semibold text-gray-700 mr-1">วันที่สั่งซื้อ:</span>
                {{ order.order_date }} น.
            </p>
        </div>
    </div>

    <!-- รูปภาพสลิปโอนเงิน -->
    {% if order.payment_image %}
    <div class="mb-6 p-6 border border-gray-300 rounded-lg shadow">
        <h2 class="text-xl font-semibold mb-4">
            สลิปโอนเงิน
        </h2>

            <!-- รูปภาพสลิปโอนเงิน -->
        <div class="flex justify-center">
            <img src="{{ order.payment_image.url }}" alt="สลิปโอนเงิน" class="max-w-[300px] w-full h-auto rounded">
        </div>
    </div>
    {% endif %}

    <!-- สินค้าในคำสั่งซื้อ -->
    <div class="p-6 border border-gray-300 rounded-lg shadow">
        <h2 class="text-xl font-semibold mb-4 flex items-center">
            สินค้าในคำสั่งซื้อ
        </h2>

        <!-- แสดงรายการสินค้า -->
        <ul class="space-y-4">
            {% for item in order.items.all %}
            <li class="flex items-center p-6 bg-white rounded-lg shadow border border-gray-100">
                <!-- รูปภาพของสินค้า -->
                <img src="{{ item.product.cover_image.url }}" alt="{{ item.product.name }}" class="w-32 h-32 rounded object-cover mr-6">

                <!-- ข้อมูลของสินค้า -->
                <div class="flex-1">
                    <p class="text-lg font-semibold">{{ item.product.name }}</p>
                    <p class="text-sm text-gray-600">รหัสสินค้า: {{ item.product.id }}</p>
                    <p class="text-sm text-gray-600">สี: {{ item.color }} | ขนาด: {{ item.size }}</p>

                    <!-- ข้อมูลราคาและจำนวนสินค้า -->
                    <p class="text-sm text-gray-600 flex justify-between">
                        <span>ราคาต่อหน่วย: <span class="text-gray-800 font-semibold">{{ item.unit_price }} บาท</span></span>
                        <span>จำนวน: <span class="text-gray-800 font-semibold">{{ item.quantity }}</span></span>
                    </p>

                    <p class="text-red-500 font-semibold flex justify-end mt-4 text-lg">
                        รวมทั้งสิน: {{ item.total_price }} บาท
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/orders/admin/order_list.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="lg:px-8 min-h-screen pb-6">
    <!-- ช่องค้นหาและ fillter -->
    <div class="gap-6 mb-6">
        <form method="GET" class="w-full max-w-6xl">
            <div class="flex flex-wrap gap-4 w-full items-end">
                <!-- Dropdown สถานะ -->
                <div class="flex-grow">
                    <label for="status" class="sr-only">สถานะ</label>
                    {{ form.status }}
                </div>

                 <!-- จากวันที่ -->
                <div class="flex-grow">
                    <label for="date_from" class="block text-sm font-medium text-gray-700">จากวันที่</label>
                    {{ form.date_from }}
                </div>

                <!-- ถึงวันที่ -->
                <div class="flex-grow">
                    <label for="date_to" class="block text-sm font-medium text-gray-700">ถึงวันที่</label>
                    {{ form.date_to }}
                </div>

                <!-- ช่องค้นหา -->
                <div class="flex-grow">
                    <label for="search" class="sr-only">ค้นหา</label>
                    {{ form.search }}
                </div>

                <!-- ปุ่มค้นหา -->
                <button type="submit"
                        class="bg-blue-500 text-white px-4 py-2 rounded-md shadow hover:bg-blue-600 transition duration-300 whitespace-nowrap h-10">
                    ค้นหา
                </button>

                <!-- ลิงก์รีเซ็ต -->
                <a href="{% url 'order_list' %}"
               class="border border-gray-400 text-gray-700 px-4 py-2 rounded-md shadow-sm hover:bg-gray-100 hover:text-gray-900 transition duration-300 whitespace-nowrap text-center">
                    รีเซ็ต
                </a>
            </div>
        </form>
    </div>

    <!-- ตารางแสดงคำสั่งซื้อ -->
    <div class="overflow-x-auto rounded-lg shadow-lg">
        <table class="min-w-full bg-white text-left">
            <thead>
                <tr class="bg-gray-300 text-gray-700">
                    <th class="px-4 py-3 min-w-[190px]">วันที่สั่งซื้อ</th>
                    <th class="px-4 py-3">หมายเลขคำสั่งซื้อ</th>
                    <th class="px-4 py-3 min-w-[150px]">ชื่อผู้สั่งซื้อ</th>
                    <th class="px-4 py-3 ">เบอร์โทร</th>
                    <th class="px-4 py-3 min-w-[150px]">ราคารวมทั้งหมด</th>
                    <th class="px-4 py-3 text-center min-w-[180px]">สถานะคำสั่งซื้อ</th>
                    <th class="px-4 py-3 text-center min-w-[150px]"></th>
                </tr>
            </thead>

            <tbody id="article-list" class="divide-y divide-gray-200">
                {% for order in page_obj %}
                    <tr class="hover:bg-gray-100 transition">
                        <td class="px-4 py-3">{{ order.order_date|date:"j M Y, H:i น." }}</td>
                        <td class="px-4 py-3">{{ order.order_code }}</td>
                        <td class="px-4 py-3">{{ order.full_name }}</td>
                        <td class="px-4 py-3">{{ order.phone }}</td>
                        <td class="px-4 py-3">{{ order.total_price }}</td>
                        <td class="px-4 py-3 text-center">
                            <span class="
                                {% if order.status == 'pending' %}
                                    bg-yellow-200 text-yellow-800
                                {% elif order.status == 'paid' %}
                                    bg-blue-200 text-blue-800
                                {% elif order.status == 'completed' %}
                                    bg-green-200 text-green-800
                                {% elif order.status == 'cancelled' %}
                                    bg-red-200 text-red-800
                                {% endif %}
                                px-3 py-1 rounded-full font-semibold">
                                {{ order.get_status_display }}
                            </span>
                        </td>
                        <td class="px-4 py-3 text-center">
                            <button
                                class="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white py-1 px-3 rounded-lg transition"
                                hx-get="{% url 'order_detail' order.id %}"
                                hx-target="#order-modal-content"
                                hx-trigger="click"
                                onclick="document.getElementById('order-modal').showModal()">
                                ดูรายละเอียด
                            </button>
                        </td>

                    </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="px-6 py-3 text-center text-gray-500">
                        ไม่มีคำสั่งซื้อ
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Modal -->
    <dialog id="order-modal" class="modal">
        <div class="modal-box w-11/12 max-w-4xl bg-gray-50 relative">
            <!-- ปุ่มปิดที่มุมขวาบน -->
            <form method="dialog" class="sticky top-0 right-0 flex justify-end">
                <button class="btn btn-sm btn-circle btn-ghost absolute right-0 top-0">✕</button>
            </form>

            <div id="order-modal-content" class=" overflow-auto">
                <!-- HTMX จะโหลดข้อมูลตรงนี้ -->
            </div>
        </div>

        <!-- ปิดเมื่อคลิกด้านนอก -->
        <form method="dialog" class="modal-backdrop">
            <button>ปิด</button>
        </form>
    </dialog>

    <!-- Pagination -->
    {% include "components/admin/pagination.html" with page_obj=page_obj query_params=query_params %}

</div>
{% endblock %}