CNStyleShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),

    path('dj-admin/', admin.site.urls),

    path('', include('shop.urls')),

    path('cart/', include('cart.urls')),

    path('account/', include('accounts.urls')),

    path('admin/', include('products.urls')),

    path('', include('articles.urls')), # มีทั้งส่วนของแอดมินและผู้้ใช้

    path('', include('orders.urls')), # มีทั้งส่วนของแอดมินและผู้้ใช้

    path('admin/', include('dashboard.urls')),
]

# เสริมสำหรับเสิร์ฟ Media Files ในโหมด Development
if settings.DEBUG:
    # สำหรับ media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # สำหรับ django-browser-reload
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

cart/urls.py
from django.urls import path
from .views import AddToCartView, CartDetailView, RemoveCartItemView, UpdateCartView

urlpatterns = [
    path('add/<int:product_id>', AddToCartView.as_view(), name='add_cart'),
    path("", CartDetailView.as_view(), name="cart_detail"),
    path('update/<int:pk>/', UpdateCartView.as_view(), name='update_cart'),
    path("remove/<int:pk>/", RemoveCartItemView.as_view(), name="remove_cart_item"),
]

dashboard/urls.py
from django.urls import path
from .views import test, AnalyzeReviewsView, DashboardView, ProductAnalysisListView

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('analyze-reviews/', AnalyzeReviewsView.as_view(), name='analyze_reviews'),
    path('product-analysis/', ProductAnalysisListView.as_view(), name='product_analysis'),


    path('test/', test, name='test'),
    # path('product-review-analysis/', ProductReviewAnalysisListView.as_view(), name='product_review_analysis'),

]

dashboard/models.py
from django.db import models
from accounts.models import UserProfile
from orders.models import OrderItem
from products.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models import Avg

class Review(models.Model):
    order_item = models.OneToOneField(OrderItem, on_delete=models.CASCADE, related_name='order_item_reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_reviews')
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='user_reviews')
    comment = models.TextField()
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        null=True, blank=True
    )
    analysis_done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # เรียกใช้ class method โดยไม่ต้องสร้างออบเจ็กต์
    @classmethod
    def get_average_rating(cls, product):
        """ ดึงค่าเฉลี่ยของคะแนนรีวิวของสินค้า """
        return cls.objects.filter(product=product).aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0

    def __str__(self):
        return f"รีวิว ID: {self.id} โดย {self.user.username}"

class ReviewAnalysis(models.Model):
    POLARITY_CHOICES = [
        ("positive", "คำเชิงบวก"),
        ("negative", "คำเชิงลบ"),
        ("neutral", "เป็นกลาง"),
    ]

    review = models.OneToOneField(Review, on_delete=models.CASCADE, related_name="analysis")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="analyses")
    score = models.FloatField()
    polarity = models.CharField(max_length=50, choices=POLARITY_CHOICES, default='neutral')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"การวิเคราะห์รีวิว {self.review.id} - ขั้วอารมณ์: {self.polarity}"

class ReviewSentiment(models.Model):
    SENTIMENT_CHOICES = [
        ('positive', 'คำเชิงบวก'),
        ('negative', 'คำเชิงลบ'),
    ]

    analysis = models.ForeignKey(ReviewAnalysis, on_delete=models.CASCADE, related_name="sentiments")
    sentiment_type = models.CharField(max_length=10, choices=SENTIMENT_CHOICES)
    word = models.CharField(max_length=255)

    def __str__(self):
        return f"วิเคราะห์ ID: {self.analysis.id} | {self.sentiment_type.capitalize()} Word: {self.word}"

orders/models.py
from django.db import models
from accounts.models import UserProfile
from products.models import Product
import uuid
from datetime import datetime
from django.utils import timezone


# ฟังก์ชันสำหรับกำหนดเส้นทางการอัปโหลดรูปภาพของสลิปโอนเงิน
def upload_to(instance,filename):
    return f"payments/{instance.id}_{filename}"

class Order(models.Model):
    PaymentMethod = (
        ('slip', 'แนบสลิป'),
    )

    STATUS = (
        ('pending', 'รอการชำระเงิน'),
        ('paid', 'จ่ายแล้ว'),
        ('completed', 'สำเร็จ'),
        ('cancelled', 'ยกเลิก'),
    )

    order_code = models.CharField(max_length=20, unique=True, editable=False) # ไม่แสดงในฟอร์มการสร้างหรือการแก้ไขข้อมูล
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='orders')
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10)
    address = models.TextField()
    total_price = models.IntegerField()
    payment_method = models.CharField(max_length=50, choices=PaymentMethod)
    payment_image = models.ImageField(upload_to=upload_to, blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='pending')
    order_date = models.DateTimeField(default=timezone.now, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"หมายเลขคำสั่งซื้อ: {self.order_code} - ชื่อ: {self.full_name} | ราคารวม: {self.total_price} บาท | สถานะ: {self.get_status_display()}"

    def save(self, *args, **kwargs):
        if not self.order_code:
            while True:
                # สร้าง order_code
                unique_part = uuid.uuid4().hex[:8]# ใช้เลขและตัวอักษร 8 หลักจาก UUID
                self.order_code = f"{datetime.now().strftime('%y%m%d')}{unique_part}"
                if not Order.objects.filter(order_code=self.order_code).exists():
                    break
        super().save(*args, **kwargs)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.IntegerField()
    color = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    unit_price = models.IntegerField()

    def __str__(self):
        return f"{self.id} | หมายเลขคำสั่งซื้อ: {self.order.order_code} | สินค้า: {self.product.name} - จำนวน: {self.quantity} | สี: {self.color} | ขนาด: {self.size} | ราคาต่อหน่วย: {self.unit_price} บาท"

    # จะถูกเรียกใช้งานได้เหมือนฟิลด์ (attribute) แทนที่จะเป็นฟังก์ชัน
    @property
    def total_price(self):
        return self.quantity * self.unit_price

dashboard/views.py
import time
from datetime import datetime, timedelta

import requests
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Count, F, Max, Q, Sum
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.timezone import now
from django.views import View
from django.views.generic import ListView, TemplateView
from collections import Counter

from orders.models import Order, OrderItem
from products.models import Product
from .models import Review, ReviewAnalysis, ReviewSentiment


def handle_rate_limit(response):
    """ ฟังก์ชันจัดการเมื่อเกิน Rate Limit และการแจ้งเตือนเวลาที่จะรีเซ็ต"""
    headers = response.headers
    remaining_second = int(headers.get('X-Custom-RateLimit-Remaining-second', 256))
    remaining_minute = int(headers.get('X-RateLimit-Remaining-minute', 120))
    remaining_day = int(headers.get('X-RateLimit-Remaining-day', 10000))
    remaining_month = int(headers.get('X-RateLimit-Remaining-month', 100000))

    # กรณีเกินลิมิตในหน่วยวินาที: รอ 1 วินาทีและดำเนินการต่อ
    if remaining_second <= 0:
        time.sleep(1)
        return None

    # กรณีเกินลิมิตในหน่วยนาที, วัน, เดือน: แจ้งเตือนและหยุดการทำงาน (คำนวณเวลาที่เหลือจนกว่า Rate Limit จะรีเซ็ต)
    if remaining_minute <= 0:
        reset_time = datetime.now() + timedelta(minutes=1) # # เพิ่ม 1 นาทีเข้าไป
    elif remaining_day <= 0:
        reset_time = datetime.now() + timedelta(days=1)
    elif remaining_month <= 0:
        reset_time = datetime.now() + timedelta(days=30)
    else:
        return None  # ไม่มีลิมิตเกิน

    # ฟอร์แมตให้เป็น string ในรูปแบบ "วัน-เดือน-ปี ชั่วโมง:นาที:วินาที"
    return f"{reset_time.strftime('%d-%m-%Y %H:%M:%S')}"

def process_review_analysis(session, review, api_url, headers):
    """ฟังก์ชันวิเคราะห์รีวิว"""

    data = {'text': review.comment}

    # เรียกใช้ API ผ่าน session
    response = session.post(api_url, headers=headers, data=data)

    if response.status_code == 200:
        result = response.json()
        sentiment = result.get('sentiment', {})
        preprocess = result.get('preprocess', {})

        print(preprocess.get('segmented',[]))

        with transaction.atomic():
            # 1. บันทึกผลลัพธ์การวิเคราะห์ลงใน ReviewAnalysis
            review_analysis = ReviewAnalysis.objects.create(
                review=review,
                product=review.product,
                score=float(sentiment.get('score', 0.0)),
                polarity=sentiment.get('polarity', 'neutral') or 'neutral'
            )

            pos_words = preprocess.get('pos', [])
            neg_words = preprocess.get('neg', [])

            # sentiments เป็น list ที่เก็บอ็อบเจ็กต์ของ ReviewSentiment
            sentiments = [
                ReviewSentiment(analysis=review_analysis, sentiment_type='positive', word=word)
                     for word in pos_words
            ] + [
                ReviewSentiment(analysis=review_analysis, sentiment_type='negative', word=word)
                     for word in neg_words
            ]

            # 2. บันทึกข้อมูลคำที่แสดงเชิงบวกหรือเชิงลบทั้งหมดในครั้งเดียว
            ReviewSentiment.objects.bulk_create(sentiments)

            # 3. อัปเดตสถานะ analysis_done เป็น True
            review.analysis_done = True
            review.save()

    elif response.status_code == 429:
        # จัดการกรณีเกินลิมิต
        limit_result = handle_rate_limit(response)
        if limit_result:
            return limit_result
    else:
        # กรณี API ตอบกลับผิดพลาดอื่น ๆ
        return JsonResponse({
            'status': 'error',
            'message': f"API returned status code {response.status_code}"
        }, status=response.status_code)

    # ไม่มีข้อผิดพลาดเกิดขึ้น
    return None

class AnalyzeReviewsView(View):
    def post(self, request, *args, **kwargs):
        # ดึงคอมเม้นต์ที่ยังไม่วิเคราะห์
        reviews = Review.objects.filter(analysis_done=False)

        # ถ้าไม่มีรีวิวที่ต้องวิเคราะห์
        if not reviews.exists():
            messages.info(request, 'ข้อมูลจากการวิเคราะห์รีวิวสินค้าล่าสุดแล้ว')
            return redirect('dashboard')

        api_url = "https://api.aiforthai.in.th/ssense"
        headers = {
            'Apikey': "JqezYBpyzRy5YrTHTTG2uMXorbtvCQ6W"
        }

        # ใช้ Session เพื่อลดการเปิด/ปิด HTTP Connection
        with requests.Session() as session:
            for review in reviews:
                # ประมวลผลการวิเคราะห์
                result = process_review_analysis(session, review, api_url, headers)

                # หากเกิดข้อผิดพลาด
                if result:
                    messages.error(request, f'เกิดข้อผิดพลาดในการวิเคราะห์ข้อความรีวิว กรุณาลองใหม่อีกครั้งในเวลา: {result}')
                    return redirect('dashboard')

        # วิเคราะห์รีวิวเสร็จสมบูรณ์
        messages.success(request, f'วิเคราะห์รีวิว {reviews.count()} รายการเสร็จสิ้น')
        return redirect('dashboard')

class DashboardView(LoginRequiredMixin, TemplateView):
    login_url = 'admin_login'
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        today = now().date()

        # 1. คำนวณยอดขายที่ status = 'completed' ของเดือนปัจจุบัน
        total_sales = Order.objects.filter(
            status="completed",
            order_date__year=today.year,   # เฉพาะปีปัจจุบัน
            order_date__month=today.month, # เฉพาะเดือนปัจจุบัน
        ).aggregate(Sum("total_price"))["total_price__sum"] or 0

        # 2. จำนวนสินค้าทั้งหมด
        total_products = Product.objects.count()

        # 3. จำนวนออเดอร์วันนี้
        orders_today = Order.objects.filter(order_date__date=today).count()

        # 4. หมวดหมู่สินค้าที่ขายดีที่สุดในเดือนนี้ (กี่ชิ้น)
        best_category = (
            OrderItem.objects.filter(
                order__status="completed",
                order__order_date__year=today.year, # เฉพาะปีปัจจุบัน
                order__order_date__month=today.month # เฉพาะเดือนปัจจุบัน
            )
            .select_related('product') # ดึงข้อมูล Product มาพร้อมกัน ผ่านฟิลด์ product ของตาราง OrderItem
            .values(category=F("product__category")) # ดึง category จาก Product แล้วเปลี่ยนชื่อคอลัมน์เป็น category
            .annotate(total_quantity=Sum("quantity")) # รวมจำนวนสินค้าที่ขายได้ ตามหมวดหมู่
            .order_by("-total_quantity")  # เรียงจากมากไปน้อย
        )

        # #นับจำนวนรีวิวที่ยังไม่ได้วิเคราะห์
        unprocessed_review_count = Review.objects.filter(analysis_done=False).count()

        # หาวันที่มีการวิเคราะห์ล่าสุด
        latest_analysis_time = ReviewAnalysis.objects.aggregate(latest_time=Max('created_at'))['latest_time']

        # 5. วิเคราะห์ความคิดเห็นสินค้าทั้งหมด
        total_reviews_product = ReviewAnalysis.objects.count()  # นับจำนวนความคิดเห็นทั้งหมด

        # นับจำนวนรีวิวแต่ละประเภท (positive, neutral, negative)
        sentiment_counts = ReviewAnalysis.objects.values('polarity').annotate(count=Count('id'))

        # สร้าง dictionary สำหรับเก็บเปอร์เซ็นต์
        sentiment_percentages = {
            'positive': 0,
            'neutral': 0,
            'negative': 0
        }

        # ถ้ามีรีวิวทั้งหมด และคำนวณเปอร์เซ็นต์ โดยปัดเศษผลลัพธ์เป็นทศนิยม 2 ตำแหน่ง
        if total_reviews_product > 0:
            for item in sentiment_counts:
                sentiment_percentages[item['polarity']] = round((item['count'] / total_reviews_product) * 100, 2)

        # 6. วิเคราะห์ความคิดเห็นตามประเภทสินค้า
        review_summary = Product.objects.values('category').annotate(
            total_reviews=Count('analyses'), # นับจำนวนรีวิวที่วิคราะห์ทั้งหมด (ReviewAnalysis) ที่เกี่ยวข้องกับสินค้าในแต่ละ category
            positive_reviews=Count('analyses', filter=Q(analyses__polarity='positive')),
            negative_reviews=Count('analyses', filter=Q(analyses__polarity='negative')),
            neutral_reviews=Count('analyses', filter=Q(analyses__polarity='neutral'))
        ).filter(total_reviews__gt=0).order_by('category') # กรองเฉพาะประเภทสินค้าที่มีรีวิว และ เรียงลำดับผลลัพธ์ตาม category

        result = [] # สร้าง list ว่างชื่อ result เพื่อเก็บผลลัพธ์ที่คำนวณได้
        for item in review_summary:
            total_reviews = item['total_reviews']

            # คำนวณเปอร์เซ็นต์
            positive_percentage = (item['positive_reviews'] / total_reviews) * 100 if total_reviews > 0 else 0
            negative_percentage = (item['negative_reviews'] / total_reviews) * 100 if total_reviews > 0 else 0
            neutral_percentage = (item['neutral_reviews'] / total_reviews) * 100 if total_reviews > 0 else 0

            result.append({
                'category': item['category'],
                'total_reviews': total_reviews,
                'positive_reviews': item['positive_reviews'],
                'negative_reviews': item['negative_reviews'],
                'neutral_reviews': item['neutral_reviews'],

                'positive_percentage': round(positive_percentage, 2),  # ปัดเศษเป็นทศนิยม 2 ตำแหน่ง
                'negative_percentage': round(negative_percentage, 2),  # ปัดเศษเป็นทศนิยม 2 ตำแหน่ง
                'neutral_percentage': round(neutral_percentage, 2)  # ปัดเศษเป็นทศนิยม 2 ตำแหน่ง
            })

        context.update(
            {
                "total_sales": total_sales,
                "total_products": total_products,
                "orders_today": orders_today,
                "best_category": best_category,
                "total_reviews_product": total_reviews_product,
                "unprocessed_review_count": unprocessed_review_count,
                "latest_analysis_time": latest_analysis_time,
                "sentiment_percentages": dict(sentiment_percentages),
                "result": result,
            }
        )
        return context

class ProductAnalysisListView(LoginRequiredMixin, ListView):

templates/dashboard/dashboard.html
{% extends 'base_admin.html' %}

{% block content %}

{% load static %}

<div class="md:px-8 min-h-screen pb-6">

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10">
        <!-- Total Sales -->
        <div class="bg-white shadow-md rounded-lg overflow-hidden w-full">
            <div class="bg-gray-800 text-white px-6 py-3 flex justify-between items-center">
                <p class="font-semibold text-lg">ยอดขายทั้งหมด</p>
                <p class="text-gray-300 text-sm">เดือนนี้</p>
            </div>
            <div class="bg-white p-6 text-center">
                <p class="text-red-600 text-4xl font-bold">฿{{ total_sales }}</p>
            </div>
        </div>

        <!-- Products -->
        <div class="bg-white shadow-md rounded-lg overflow-hidden w-full">
            <a href="{% url 'product_list' %}">
                <div class="bg-gray-800 text-white px-6 py-3 flex justify-between items-center">
                    <p class="font-semibold text-lg">สินค้า</p>
                    <p class="text-gray-300 text-sm">ทั้งหมด</p>
                </div>
                <div class="bg-white p-6 text-center">
                    <p class="text-red-600 text-4xl font-bold">{{ total_products }} </p>
                </div>
            </a>
        </div>

        <!-- Orders -->
        <div class="bg-white shadow-md rounded-lg overflow-hidden w-full">
            <a href="{% url 'order_list' %}">
                <div class="bg-gray-800 text-white px-6 py-3 flex justify-between items-center">
                    <p class="font-semibold text-lg">คำสั่งซื้อ</p>
                    <p class="text-gray-300 text-sm">วันนี้</p>
                </div>
                <div class="bg-white p-6 text-center">
                    <p class="text-red-600 text-4xl font-bold">{{ orders_today }}</p>
                </div>
            </a>
        </div>

        <!-- Best Selling Categories -->
        <div class="bg-white shadow-md rounded-lg overflow-hidden w-full col-span-1 px-6 ">
             <div class="py-3 border-b-2 border-gray-300">
                <p class="text-gray-800 font-semibold mb-2 text-lg">ประเภทสินค้าที่ขายดีที่สุด</p>
                <p class="text-gray-500  text-sm">เดือนนี้</p>
            </div>
            {% if best_category %}
                <ul class="space-y-3 py-3 list-disc pl-5 max-h-[250px] overflow-y-auto">
                    {% for category in best_category %}
                        <li class="text-gray-700 font-medium hover:bg-gray-100 rounded-lg p-2 transition-all duration-200 ease-in-out">
                            <span class="font-semibold text-gray-900">{{ category.category|capfirst }}</span> -
                            <span class="text-red-600">{{ category.total_quantity }} ชิ้น</span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="text-gray-600 text-sm text-center py-4">ไม่มีข้อมูลการขายสำหรับเดือนนี้</p>
            {% endif %}

        </div>

        <!-- Feedback Analysis -->
        <div class=" bg-white shadow-md rounded-lg overflow-hidden w-full pb-6 col-span-2 ">
            <div class="flex justify-between items-center border-b-2 border-gray-300 py-4 px-6 ">
                <div>
                    <!-- Title Section -->
                    <p class="text-gray-800 uppercase font-semibold text-lg">วิเคราะห์ข้อความรีวิวของสินค้าทั้งหมด</p>

                    <!-- แสดงวันที่วิเคราะห์ล่าสุด และจำนวนรีวิวที่ยังไม่ได้วิเคราะห์ -->
                    <div class="text-gray-600 text-xs flex items-center space-x-2 mt-2">
                        <span>วันที่วิเคราะห์ล่าสุด:
                            {% if latest_analysis_time %}
                                {{ latest_analysis_time|date:"d/m/Y H:i" }}
                            {% else %}
                                ไม่มีการวิเคราะห์ข้อมูล
                            {% endif %}
                        </span>

                        {% if unprocessed_review_count > 0 %}
                            <span class="text-red-600 text-xs">
                                ( มีรีวิวที่ยังไม่ได้วิเคราะห์จำนวน {{ unprocessed_review_count }} ข้อความ )
                            </span>
                        {% else %}
                            <span class="text-green-600 text-xs">
                                ( ล่าสุด )
                            </span>
                        {% endif %}
                    </div>
                </div>

                <!-- Analyze Reviews Button  analyze_reviews  (ลอง test) -->
                <form id="analyzeForm" action="{% url 'analyze_reviews' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="bg-blue-400 text-white px-4 py-2 rounded-lg hover:bg-blue-500 transition duration-300 ease-in-out">
                        <span id="btnText">อัปเดต</span>
                        <span id="spinner" class="loading loading-spinner hidden"></span>
                    </button>
                </form>
            </div>

            <!-- แสดง messages success/error-->
            {% include "components/alert/alert_dashbord.html" with messages=messages %}

            <p class="text-gray-800 font-bold text-xl text-center mt-4 ">ข้อความรีวิวมีทั้งหมด <span class="text-red-600">{{ total_reviews_product }}</span>  ข้อความ</p>

            <div class="mt-4 bg-gray-800 text-white rounded-lg px-6 py-4 md:mx-20 mx-4 md:p-6 font-bold text-lg md:text-2xl space-y-4">
                <div class="flex items-center justify-between">
                    <span class="flex items-center text-green-400">
                        <img src="{% static 'images/happy.svg' %}" alt="happy Logo" class="w-6 h-6 md:w-8 md:h-8 mr-2">
                        Positive
                    </span>
                    <span class="font-bold">{{ sentiment_percentages.positive }} %</span>
                </div>

                <div class="flex items-center justify-between">
                    <span class="flex items-center text-yellow-400">
                        <img src="{% static 'images/neutral.svg' %}" alt="neutral Logo" class="w-6 h-6 md:w-8 md:h-8 mr-2">
                        Neutral
                    </span>
                    <span class="font-bold">{{ sentiment_percentages.neutral }} %</span>
                </div>

                <div class="flex items-center justify-between">
                    <span class="flex items-center text-red-400">
                        <img src="{% static 'images/angry.svg' %}" alt="angry Logo" class="w-6 h-6 md:w-8 md:h-8 mr-2">
                        Negative
                    </span>
                    <span class="font-bold">{{ sentiment_percentages.negative }} %</span>
                </div>
            </div>
        </div>
    </div>

    <div class="container mx-auto bg-white shadow-md rounded-lg overflow-hidden w-full mt-6 sm:mt-8 lg:mt-10 p-6">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-semibold ">วิเคราะห์ความคิดเห็นตามประเภทสินค้า</h2>
            <a href="{% url 'product_analysis' %}" class=" text-blue-500 hover:text-blue-700">
                ดูวิเคราะห์ความคิดเห็นแต่ละสินค้า
            </a>
        </div>

        <!-- เส้นแบ่ง -->
        <hr class="border-t-2 border-gray-300 mb-4">

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {% for data in result %}

                <div class="bg-stone-100 shadow-md rounded-lg overflow-hidden p-6">
                    <h3 class="text-md font-semibold mb-2">{{ data.category|capfirst }}</h3>
                    <p class="text-gray-600 text-xs mb-2">จำนวนรีวิวทั้งหมด {{ data.total_reviews }} ข้อความ</p>
                    <hr class="border-t-2 border-gray-200 mb-4">

                    <ul class="space-y-2 font-semibold">
                        <li class="flex items-center justify-between">
                            <span class="flex items-center text-green-400">
                                <img src="{% static 'images/happy.svg' %}" alt="happy Logo" class="w-5 h-5 md:w-7 md:h-7 mr-2">
                                Positive
                            </span>
                            <span>{{ data.positive_percentage }}%</span>
                        </li>
                        <li class="flex items-center justify-between">
                            <span class="flex items-center text-yellow-500">
                                <img src="{% static 'images/neutral.svg' %}" alt="happy Logo" class="w-5 h-5 md:w-7 md:h-7 mr-2">
                                Neutral
                            </span>
                            <span>{{ data.neutral_percentage }}%</span>
                        </li>
                        <li class="flex items-center justify-between">
                            <span class="flex items-center text-red-600">
                                <img src="{% static 'images/angry.svg' %}" alt="happy Logo" class="w-5 h-5 md:w-7 md:h-7 mr-2">
                                Negative
                            </span>
                            <span>{{ data.negative_percentage }}%</span>
                        </li>
                    </ul>
                </div>
            {% endfor %}
        </div>

    </div>

</div>

<script>
    document.getElementById("analyzeForm").addEventListener("submit", function() {
        document.getElementById("btnText").classList.add("hidden");
        document.getElementById("spinner").classList.remove("hidden");
        document.getElementById("submitBtn").disabled = true;
    });
</script>
{% endblock %}